services:
  db:
    image: postgres:15
    container_name: ewallet_postgres
    restart: always
    environment:
      POSTGRES_USER: ewallet_user
      POSTGRES_PASSWORD: ewallet_pass
      POSTGRES_DB: ewallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - appnet

  redis:
    image: redis:7
    container_name: ewallet_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - appnet

  signsafe:
    build:
      context: .
      dockerfile: ./go-signsafe/Dockerfile
    container_name: go_signsafe
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000" # map ke luar jika dibutuhkan
    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ewallet_user
      DB_PASS: ewallet_pass
      DB_NAME: ewallet_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - appnet

  signsafe-jwt:
    build:
      context: .
      dockerfile: ./go-signsafe-jwt/Dockerfile
    container_name: go_signsafe_jwt
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ewallet_user
      DB_PASS: ewallet_pass
      DB_NAME: ewallet_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: ./sveltekit-signsafe/Dockerfile
    container_name: sveltekit_signsafe
    depends_on:
      - signsafe
      - signsafe-jwt
    restart: always
    ports:
      - "4173:4173"
    networks:
      - appnet
    environment:
      VITE_API1_BASE_URL: http://signsafe:8000/api
      VITE_API2_BASE_URL: http://signsafe-jwt:8001/api

volumes:
  db_data:
  redis_data:

networks:
  appnet:
    driver: bridge
